import requests
from requests.auth import HTTPBasicAuth
import re

from datetime import date

# API URL 
API_URL = "https://horizonweb-cloud.visma.lv/REST_H34764033/rest/TNdmPvzRekS/template/49"
USERNAME = "restdemo_davis"
PASSWORD = "uZKWVM#p8kUvN!"

date_today = date.today()

def create_xml(invoice_number, date, due_date, total):
    return f"""<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <resource>
        <description>Jauna ieraksta sagatave atbilstoši dokumenta tipam</description>
        <entity
            xmlns="TNdmPvzRekS.xsd"
            xmlns:xlink="http://www.w3.org/1999/xlink"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="TNdmPvzRekS.xsd ../TNdmPvzRekS.xsd">
            <PK_DOKT>
                <href>/rest/TdmDocType/49</href>
            </PK_DOKT>
            <PAMV_ID>2719</PAMV_ID>
            <COUNTER/>
            <PK_DOK/>
            <PK_IESTADE>
                <href>/rest/TdmDIestadeBL/8</href>
            </PK_IESTADE>
            <STATUSS>1</STATUSS>
            <PK_ESPATS>1</PK_ESPATS>
            <PK_R_ES/>
            <PK_KLIENTS>
                <href>/rest/TDdmCustomer/12</href>
            </PK_KLIENTS>
            <PK_R_KL/>
            <PK_PVNK>
                <href>/rest/TdmPvnKat/1</href>
            </PK_PVNK>
            <DAT_GRP> 
                <date>{date}</date> <!-- DATUMS -->
                <interim>00</interim>
            </DAT_GRP>
            <DAT_DOK>{date}</DAT_DOK>
            <DAT_GRAM>{date}</DAT_GRAM>
            <PK_VAL>
                <href>/rest/TsdmValName/3</href>
            </PK_VAL>
            <DOK_NR>{invoice_number}</DOK_NR>
            <VIRZIENS>2</VIRZIENS>
            <SUMMA></SUMMA> <!-- DATUMS -->
            <PAMAT/>
            <PK_APMVAL>
                <href>/rest/TsdmValName/3</href>
            </PK_APMVAL>
            <PIEZIMES/>
            <TIPS>1</TIPS>
            <PK_SAISDOK/>
            <SUMMA_PV>{total}</SUMMA_PV>
            <SUMMA_BEZPVN/>
            <SUMMA_APM>{total}</SUMMA_APM>
            <SUMMA_APMP></SUMMA_APMP>
            <SUMMA_APMN></SUMMA_APMN>
            <SUMMA_SAM>{total}</SUMMA_SAM>
            <SUMMA_PVN_REV></SUMMA_PVN_REV>
            <SUMMA_PVN/>
            <DOK_PVN/>
            <SUM_PAPM/>
            <SUM_PPVN/>
            <PK_PROJ>
                <href>/rest/TdmProject/1</href>
            </PK_PROJ>
            <DOK_NR2/>
            <DOK_SERIJA/>
            <DOK_REGNR/>
            <PK_LIG/>
            <APM_TERM>{due_date}</APM_TERM>
            <DAT_REG>{date}</DAT_REG>
            <DAR_VIETA>0</DAR_VIETA>
            <PK_PARD/>
            <REFNR/>
            <SODS_APM/>
            <PK_APRSTATUSS>
                <href>/rest/TdmApritStatussBL/1</href>
            </PK_APRSTATUSS>
            <SADAL_APM></SADAL_APM>
            <PVN_SAMAZ/>
            <PVNAPL_SAMAZ/>
            <SUM_NEAPLIEK/>
            <ATT_PVN_SUM/>
            <ATT_PVN_APLIEK/>
            <NEPIESAIST/>
            <NEPIESAIST_PV/>
            <SUMMA_PIES></SUMMA_PIES>
            <SUMMA_PIESP></SUMMA_PIESP>
            <SUMMA_PIESN></SUMMA_PIESN>
            <SUMMA_PIES_PV></SUMMA_PIES_PV>
            <SUMMA_PIES_PR/>
            <NORCNT>0</NORCNT>
            <NORMINUSS>0</NORMINUSS>
            <PIES_DLIST/>
            <OUT_AR>0</OUT_AR>
            <PK_DSEKT/>
            <OUT_PVNDEKL>0</OUT_PVNDEKL>
            <NOR_VIRZIENS>0</NOR_VIRZIENS>
            <PAP_NR/>
            <SODS_SAK/>
            <SODS_BEIG/>
            <SUMMA_APM_PV>{total}</SUMMA_APM_PV>
            <VKAVNAPR>0</VKAVNAPR>
            <DAT_PIES_LAST>3000-01-01</DAT_PIES_LAST>
            <PK_DAIZP_ALG/>
            <KURSS_APM>1</KURSS_APM>
            <KOREKCSAIS/>
            <PAMAT_NOKONV/>
            <PK_PARGR_TYPE/>
            <PK_KLKARTE/>
            <CHK_NUM/>
            <PK_CHQ/>
            <RN_VEIDS/>
            <OBL_SAK_CENA/>
            <SKONTO_ATL_DOK/>
            <SKONTO_FILL/>
            <PR_ATT_PVN_SUM/>
            <PR_ATT_PVN_APLIEK/>
            <PR_PVN_SAMAZ/>
            <PR_PVNAPL_SAMAZ/>
            <REK_ROW_PERT_DAT/>
            <USRSERIJA/>
            <FILL_IPASIBAS/>
            <DEPNOM_EXEC/>
            <LIG_PAMV_ID/>
            <LIG_SANFILTER/>
            <RND_PK_PROJ/>
            <RND_PK_OBJ1/>
            <RND_PK_OBJ2/>
            <RND_PK_OBJ3/>
            <RND_PK_OBJ4/>
            <PVND_ATT_VEIDS/>
            <BRIVDIR/>
            <NdmPvzAddition>
                <PK_DOK/>
                <PK_ADRESE/>
                <PK_APMV/>
                <DAT_PIEG/>
                <AUTO_NR/>
                <AUTO_VAD/>
                <PVN_TIPS>0</PVN_TIPS>
                <ATLAIDE/>
                <PK_SOF/>
                <PK_AUTOM/>
                <PK_ORDER/>
                <PAZIMES/>
                <PROCN/>
                <PK_SANEM/>
                <PIELIKUMS/>
                <PK_VALSTS/>
                <PK_DARVEIDS/>
                <PK_TRANVEIDS/>
                <PK_PIEGVEIDS/>
                <DAR_ES_PAZ>0</DAR_ES_PAZ>
                <K_TIPS>43</K_TIPS>
                <PK_STRV/>
                <PK_FINAN/>
                <PK_IZMP/>
                <PK_DIM1/>
                <PK_DIM2/>
                <PK_DIM3/>
                <PK_NDARAPR>
                    <href>/rest/TdmNDarAprBL/6</href>
                </PK_NDARAPR>
                <IEP_PAK/>
                <PK_REISS/>
                <KILOMETRI/>
                <DAT_IZSUT/>
                <PK_PAT/>
                <PK_KLKPERS/>
                <PK_KOM/>
                <SENT_TO_REP>0</SENT_TO_REP>
                <IS_MEDNIS_PNA>0</IS_MEDNIS_PNA>
                <MKP_SASAISTE_MODE>0</MKP_SASAISTE_MODE>
                <PNA_SUMMA_BEZ_PVN/>
                <CAN_EDIT_LIG>1</CAN_EDIT_LIG>
                <REPO_ID/>
                <HASEDOK>0</HASEDOK>
                <PK_GIFTCARD/>
                <PUNKTI/>
                <SKON_PROC/>
                <SKON_DAT/>
                <SKON_DIENAS/>
                <PK_PVNNOR/>
                <GAR_DATUMS/>
                <KOPDAUDZ/>
                <KOPSUMMA/>
                <PK_IMPDOK/>
                <ADRESE/>
                <AUTDIMK>0</AUTDIMK>
                <PK_ORD/>
                <BUDZREZ/>
                <PK_AVKONTS/>
                <PK_DOKTMET/>
                <PK_CSBKSOBJ/>
                <PK_IEGPRJLK/>
                <PK_SOF2/>
                <PK_PIEGV/>
                <NOMPARTSAD/>
                <PPK_STRV/>
                <PPK_IZMP/>
                <PPK_FINAN/>
                <PPK_DIM1/>
                <PPK_DIM2/>
                <PPK_DIM3/>
                <PPK_PROJ/>
            </NdmPvzAddition>
            <NPvzPvnRowsBl/>
            <SanRekIzmRows/>
            <dmDokStrvBL/>
            <dmDApmSadRBL/>
            <PvzNorGrBl/>
            <dmPiesaistesRBL>
                <cdsVRows/>
            </dmPiesaistesRBL>
            <dmDNorekBL/>
            <dmDNorekPrSadalRBL/>
            <dmNdocIpasBL/>
            <qryPamat/>
            <tblRindas>
                <row>
                    <RN>1</RN>
                    <NPK>1</NPK>
                    <RN_VEIDS>3</RN_VEIDS>
                    <PK_NOM>5</PK_NOM>
                    <PK_BARKODS/>
                    <KODS>P</KODS>
                    <BAR_KODS/>
                    <KAT_KODS/>
                    <NOSAUK>REMONTS</NOSAUK>
                    <NOSAUKSV/>
                    <NOSAUK2/>
                    <PK_V1>13</PK_V1>
                    <PK_V2/>
                    <PK_V3/>
                    <M_ATT12/>
                    <M_ATT13/>
                    <ATLUZSK>0</ATLUZSK>
                    <RAZ_VEIDS>0</RAZ_VEIDS>
                    <PK_DOK>
                        <href>/rest/TNdmPvzRekS/5253</href>
                    </PK_DOK>
                    <PK_VIEN>13</PK_VIEN>
                    <V_KODS>gb</V_KODS>
                    <M_ATT>1</M_ATT>
                    <PK_LIKME>1</PK_LIKME>
                    <PROCN></PROCN>
                    <DAUDZ>1</DAUDZ>
                    <FCENA></FCENA>
                    <CENA></CENA>
                    <ATLAIDE></ATLAIDE>
                    <SUMMA>{total}</SUMMA>
                    <TEKSTS/>
                    <SUMMA_BPVN></SUMMA_BPVN>
                    <D_MISSING/>
                    <CENA_TIPS>0</CENA_TIPS>
                    <SUMMA_IEP></SUMMA_IEP>
                    <PVNUZSK></PVNUZSK>
                    <PK_PIESKGR/>
                    <SVARS/>
                    <PGR_KODS/>
                    <LG_RES/>
                    <BRUTO/>
                    <CENA_OLD/>
                    <SUMMA_STAT/>
                    <PK_VALSTS/>
                    <PK_CENVEID/>
                    <CENV_KODS/>
                    <CENV_NOSAUK/>
                    <DATUMS>{date}</DATUMS>
                    <TEMPERAT/>
                    <DAUDZ_S/>
                    <PK_ROW/>
                    <PK_PAS/>
                    <PASNR/>
                    <PK_STRV/>
                    <PK_IZMP/>
                    <PK_FINAN/>
                    <PK_DIM1/>
                    <PK_DIM2/>
                    <PK_DIM3/>
                    <DAUDZ_IZS/>
                    <DATNO>{date}</DATNO>
                    <DATLIDZ>{due_date}</DATLIDZ>
                    <PK_PROJ/>
                    <NPITIPS>0</NPITIPS>
                    <PK_KONTS>200</PK_KONTS>
                    <PK_NPIK>334</PK_NPIK>
                    <NPI_LOCK/>
                    <PK_OBJ1/>
                    <PK_OBJ2/>
                    <PK_OBJ3/>
                    <PK_OBJ4/>
                    <PK_OBJ5/>
                    <PK_OBJ6/>
                    <PK_OBJ7/>
                    <PK_VAR/>
                    <SER_UZSK>0</SER_UZSK>
                    <SER_DOKT/>
                    <CHK_NUM/>
                    <RPN_OBL/>
                    <PK_SERNUM/>
                    <PK_PARTNUM/>
                    <PARTSTAT/>
                    <PK_DNORGRP>1</PK_DNORGRP>
                    <IS_MEDNIS_PNA/>
                    <MKP_SASAISTE_MODE/>
                    <PART_UNIQ/>
                    <ATL_AKC/>
                    <SAKCENA></SAKCENA>
                    <DAT_TERM>3000-01-01</DAT_TERM>
                    <PK_PVNATSAM/>
                    <PROCAT/>
                    <PK_LPAKRND/>
                    <PDER_TERM_OBL/>
                    <SUMMA_STAT_DOKVAL/>
                    <DAUDZD/>
                    <GAR_DATUMS/>
                    <NUMURS/>
                    <DAT_DERIG/>
                    <AKCMARK/>
                    <SERTPART/>
                    <PARTPIEZ/>
                    <DAT_RAZ/>
                    <STATUSS/>
                    <RPN/>
                    <CENA_PARD/>
                    <SUMMA_PVN>0</SUMMA_PVN>
                    <DAUDZ2/>
                    <PK_VIENP/>
                    <D_MISSING2/>
                    <IZM_PAZ>1</IZM_PAZ>
                    <IZM_PIES/>
                    <PK_PIEG/>
                    <NPG_ITM_CODE/>
                    <PROJ_PAPKODS/>
                    <SUMMABUDZ/>
                    <BUDZGADS/>
                    <BLIVUMS/>
                    <KONCEN/>
                    <KONSUM/>
                    <KONDAUDZ/>
                    <KONPOZ/>
                    <DAUDZ11>1</DAUDZ11>
                    <DAUDZ12/>
                    <DAUDZ13/>
                    <PAMATRN/>
                    <RECALCDEP/>
                    <ODIM1_KODS/>
                    <ODIM1_NOSAUK/>
                    <ODIM1_STATUSS/>
                    <ODIM2_KODS/>
                    <ODIM2_NOSAUK/>
                    <ODIM2_STATUSS/>
                    <ODIM3_KODS/>
                    <ODIM3_NOSAUK/>
                    <ODIM3_STATUSS/>
                    <ODIM4_KODS/>
                    <ODIM4_NOSAUK/>
                    <ODIM4_STATUSS/>
                    <ODIM4_FIELD_1/>
                    <ODIM4_FIELD_2/>
                </row>
            </tblRindas>
            <qrySubRindas/>
        </entity>
    </resource>
    """.encode('utf-8')

def send_invoice_to_api(xml_data):
    """Funkcija, kas nosūta XML uz REST API, izmantojot HTTP POST pieprasījumu."""
    response = requests.post(API_URL, data=xml_data, headers={'Content-Type': 'application/xml'}, auth=HTTPBasicAuth(USERNAME, PASSWORD))
    if response.status_code == 200:
        print("Successfully")
    else:
        print(f"Failed: {response.status_code} - {response.text}")


def clean_date(date_str):
    # Regex, kas meklē datumus formātā dd.mm.yyyy
    date_pattern = r"\b(\d{1,2})\.(\d{1,2})\.(\d{4})\b"
    match = re.search(date_pattern, date_str)
    
    if match:
        day, month, year = match.groups()
        return f"{year}-{int(month):02d}-{int(day):02d}."
    else:
        return date_today

